package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/karchx/goQL/graph/model"
	"github.com/karchx/goQL/models"
)

// CreateBook is the resolver for the createBook field.
func (r *mutationResolver) CreateBook(ctx context.Context, input *model.NewBook) (*model.Book, error) {
	book := models.Book{
		Title:         input.Title,
		Author:        input.Author,
		PublishedYear: &input.PublishedYear,
	}

	if err := r.Handler.CreateBook(&book); err != nil {
		return nil, err
	}
	return book.ToGraphModel(), nil
}

// Books is the resolver for the books field.
func (r *queryResolver) Books(ctx context.Context) ([]*model.Book, error) {
	books, err := r.Handler.GetBooks()
	if err != nil {
		return nil, err
	}
	return models.ToGraphModelBooks(*books), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
