// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Book struct {
	ID            string `json:"id"`
	Title         string `json:"title"`
	Author        string `json:"author"`
	PublishedYear int32  `json:"publishedYear"`
}

type Mutation struct {
}

type NewBook struct {
	Title         string `json:"title"`
	Author        string `json:"author"`
	PublishedYear int32  `json:"publishedYear"`
}

type Query struct {
}
